window.FICHES = [
  {
    id: "astronotus-ocellatus",   
    nomScientifique: "Astronotus ocellatus",
    nomCommun: "Oscar",
    ordre: "Cichliformes",
    famille: "Cichlidae",
    genre: "Astronotus",
    continent: "Amérique du Sud",
    pays: ["Brésil", "Pérou", "Colombie"],
    page: "fiche/Astronotus-ocellatus.html",
    image: "img/Astronotus-ocellatus/Astronotus-ocellatus.jpeg"
  },
  {
    id: "poecilia-reticulata",
    nomScientifique: "Poecilia reticulata",
    nomCommun: "Guppy",
    ordre: "Cyprinodontiformes",
    famille: "Poeciliidae",
    genre: "Poecilia",
    continent: "Amérique du Sud",
    pays: ["Venezuela", "Guyana", "Brésil"],
    page: "fiche/Poecilia-reticulata.html",
    image: "img/Poecilia-reticulata/Poecilia-reticulata.jpeg"
  },
  {
    id: "andinoacara-rivulatus",
    nomScientifique: "Andinoacara rivulatus",
    nomCommun: "Green Terror",
    ordre: "Cichliformes",
    famille: "Cichlidae",
    genre: "Andinoacara",
    continent: "Amérique du Sud",
    pays: ["Équateur", "Pérou"],
    page: "fiche/Andinoacara-rivulatus.html",
    image: "img/Adinoacara-rivulatus/imgAdinoacararivulatus.jpeg"
  },
  {
    id: "bedotia-geayi",
    nomScientifique: "Bedotia geayi",
    nomCommun: "Bedotia de Geay",
    ordre: "Atheriniformes",
    famille: "Bedotiidae",
    genre: "Bedotia",
    continent: "Afrique",                    
    pays: ["Madagascar"],
    page: "fiche/Bedotia-geayi.html",
    image: "img/Bedotia-geayi/Bedotia-geayi.jpeg"
  },
  {
    id: "cyrtocara-moorii",
    nomScientifique: "Cyrtocara moorii",
    nomCommun: "Dauphin bleu",
    ordre: "Cichliformes",
    famille: "Cichlidae",
    genre: "Cyrtocara",
    continent: "Afrique",
    pays: ["Malawi"],
    page: "fiche/Cyrtocara-moorii.html",
    image: "img/Cyrtocara-moorii/imgCyrtocaramoorii.jpeg"
  },
  {
    id: "gymnocorymbus-ternetzi",
    nomScientifique: "Gymnocorymbus ternetzi",
    nomCommun: "Tétra veuve noire",
    ordre: "Characiformes",
    famille: "Characidae",
    genre: "Gymnocorymbus",
    continent: "Amérique du Sud",
    pays: ["Brésil", "Bolivie", "Paraguay"],
    page: "fiche/Gymnocorymbus-ternetzi.html",
    image: "img/Gymnocorymbus-ternetzi/Gymnocorymbus-ternetzi.jpeg"
  },
  {
    id: "herichthys-carpintis",
    nomScientifique: "Herichthys carpintis",
    nomCommun: "Cichlidé perlé du Texas",
    ordre: "Cichliformes",
    famille: "Cichlidae",
    genre: "Herichthys",
    continent: "Amérique du Nord",
    pays: ["Mexique"],
    page: "fiche/Herichthys-carpintis.html",
    image: "img/Herichthys-carpintis/imgHerichthyscarpintis.jpeg"
  },
  {
    id: "heros-efasciatus",
    nomScientifique: "Heros efasciatus",
    nomCommun: "Severum",
    ordre: "Cichliformes",
    famille: "Cichlidae",
    genre: "Heros",
    continent: "Amérique du Sud",
    pays: ["Brésil", "Pérou"],
    page: "fiche/Heros-efasciatus.html",
    image: "img/Heros-efasciatus/imgHerosefasciatus.jpeg"
  },
  {
    id: "limia-perugiae",
    nomScientifique: "Limia perugiae",
    nomCommun: "Limia de Perugia",
    ordre: "Cyprinodontiformes",
    famille: "Poeciliidae",
    genre: "Limia",
    continent: "Amérique du Nord",       
    pays: ["République dominicaine", "Haïti"], 
    page: "fiche/Limia-perugiae.html",
    image: "img/Limia-perugiae/Limia-perugiae.jpeg"
  },
  {
    id: "hyphessobrycon-anisitsi",
    nomScientifique: "Hyphessobrycon anisitsi",
    nomCommun: "Tétra de Buenos Aires",
    ordre: "Characiformes",
    famille: "Characidae",
    genre: "Hyphessobrycon",
    continent: "Amérique du Sud",
    pays: ["Argentine", "Brésil", "Paraguay", "Uruguay"],
    page: "fiche/Hyphessobrycon-anisiti.html",
    image: "img/Hyphessobrycon-anisitsi/imgHyphessobryconanisitsi.jpeg"
  },
  {
    id: "maskaheros-argenteus",
    nomScientifique: "Maskaheros argenteus",
    nomCommun: "Cichlidé argent",
    ordre: "Cichliformes",
    famille: "Cichlidae",
    genre: "Maskaheros",
    continent: "Amérique du Nord",
    pays: ["Mexique"],
    page: "fiche/Maskaheros-argenteus.html",
    image: "img/Maskaheros-argenteuse/Maskaheros-argenteus.jpeg"
  },
  {
    id: "parachromis-managuensis",
    nomScientifique: "Parachromis managuensis",
    nomCommun: "Cichlidé jaguar",
    ordre: "Cichliformes",
    famille: "Cichlidae",
    genre: "Parachromis",
    continent: "Amérique du Nord",
    pays: ["Honduras", "Nicaragua", "Costa Rica"],
    page: "fiche/Parachromis-managuensis.html",
    image: "img/Parachromis-managuensis/Parachromis-managuensis.jpg"
  },
  {
    id: "poecilia-wingei",
    nomScientifique: "Poecilia wingei",
    nomCommun: "Guppy Endler",
    ordre: "Cyprinodontiformes",
    famille: "Poeciliidae",
    genre: "Poecilia",
    continent: "Amérique du Sud",
    pays: ["Venezuela"],
    page: "fiche/Poecilia-wingei.html",
    image: "img/Poecilia-wingei/Poecilia-wingei.jpeg"
  },
  {
    id: "poecilia-obscura",
    nomScientifique: "Poecilia obscura",
    nomCommun: "Guppy de Trinidad",
    ordre: "Cyprinodontiformes",
    famille: "Poeciliidae",
    genre: "Poecilia",
    continent: "Amérique du Sud",
    pays: ["Trinité-et-Tobago"],
    page: "fiche/Poecilia-obscura.html",
    image: "img/Poecilia-obscura/Poecilia-obscura.PNG"
  },
  {
    id: "poecilia-mexicana",
    nomScientifique: "Poecilia mexicana",
    nomCommun: "Molly mexicain",
    ordre: "Cyprinodontiformes",
    famille: "Poeciliidae",
    genre: "Poecilia",
    continent: "Amérique du Nord",
    pays: ["Mexique"],
    page: "fiche/Poecilia-mexicana.html",
    image: "img/Poecilia-mexicana/imgPoeciliamexicana.jpeg"
  },
  {
    id: "pterophyllum-scalaire",
    nomScientifique: "Pterophyllum scalare",
    nomCommun: "Scalaire",
    ordre: "Cichliformes",
    famille: "Cichlidae",
    genre: "Pterophyllum",
    continent: "Amérique du Sud",
    pays: ["Brésil", "Pérou", "Colombie"],
    page: "fiche/Pterophyllum-scalaire.html",
    image: "img/Pterophyllum-scalaire/Pterophyllum-scalaire.jpeg"
  },
  {
    id: "xiphophorus-nezahualcoyotl",
    nomScientifique: "Xiphophorus nezahualcoyotl",
    nomCommun: "Xipho de Nezahualcoyotl",
    ordre: "Cyprinodontiformes",
    famille: "Poeciliidae",
    genre: "Xiphophorus",
    continent: "Amérique du Nord",
    pays: ["Mexique"],
    page: "fiche/Xiphophorus-nezahualcotl.html",
    image: "img/Xiphophorus-nezahualcoyotl/Xiphophorus-nezahualcoyotl.jpeg"
  },
  {
    id: "uaru-amphiacanthoides",
    nomScientifique: "Uaru amphiacanthoides",
    nomCommun: "Uaru",
    ordre: "Cichliformes",
    famille: "Cichlidae",
    genre: "Uaru",
    continent: "Amérique du Sud",
    pays: ["Brésil", "Colombie", "Guyane"],
    page: "fiche/Uraru-amphiacanthoides.html",
    image: "img/Urau-amphiacanthoides/imgUrauamphiacanthoides.jpeg"
  },
  {
    id: "mikrogeophagus-altispinosa",
    nomScientifique: "Mikrogeophagus altispinosus",
    nomCommun: "Cichlidé nain bolivien",
    ordre: "Cichliformes",
    famille: "Cichlidae",
    genre: "Mikrogeophagus",
    continent: "Amérique du Sud",
    pays: ["Bolivie", "Brésil"],
    page: "fiche/Mikrogeophagus-altispinosus.html",
    image: "img/Mikrogeophagus-altispinosus/imgMikrogeophagusaltispinosus.jpeg"
  },
  {
    id: "rocio-octofasciata",
    nomScientifique: "Rocio octofasciata",
    nomCommun: "Jack Dempsey",
    ordre: "Cichliformes",
    famille: "Cichlidae",
    genre: "Rocio",
    continent: "Amérique du Nord",
    pays: ["Mexique", "Honduras", "Guatemala"],
    page: "fiche/Rocio-octofasciata.html",
    image: "img/Rocio-octofasciata/imgRociooctofasciata.jpeg"
  },
  {
    id: "rasbora-hengeli",
    nomScientifique: "Trigonostigma hengeli",
    nomCommun: "Rasbora hengeli",
    ordre: "Cypriniformes",
    famille: "Cyprinidae",
    genre: "Trigonostigma",
    continent: "Asie",
    pays: ["Indonésie"],
    page: "fiche/Rasbora-hengeli.html",
    image: "img/Trigonostigma-hengeli/Triginostigma-hengeli.PNG"
  },
  {
    id: "crossocheilus-siamensis",
    nomScientifique: "Crossocheilus siamensis",
    nomCommun: "Mangeur d’algues siamois",
    ordre: "Cypriniformes",
    famille: "Cyprinidae",
    genre: "Crossocheilus",
    continent: "Asie",
    pays: ["Thaïlande", "Laos", "Cambodge"],
    page: "fiche/Crossocheilus-siamensis.html",
    image: "img/Crossocheilus-siamensis/Crossocheilus-siamensis.PNG"
  },
  {
    id: "trichogaster-leeri",
    nomScientifique: "Trichogaster leeri",
    nomCommun: "Gourami perlé",
    ordre: "Anabantiformes",
    famille: "Osphronemidae",
    genre: "Trichogaster",
    continent: "Asie",
    pays: ["Thaïlande", "Malaisie", "Indonésie"],
    page: "fiche/Trichogaster-leerii.html",
    image: "img/Trichopodus-leerii/Trichopodus-leerii.jpeg"
  },
  {
    id: "neolamprologus-pulcher",
    nomScientifique: "Neolamprologus pulcher",
    nomCommun: "Cichlidé princesse de Zambie",
    ordre: "Cichliformes",
    famille: "Cichlidae",
    genre: "Neolamprologus",
    continent: "Afrique",
    pays: ["Zambie"],
    page: "fiche/Neolamprologus-pulcher.html",
    image: "img/Neolamprologus-brichardi/imgNeolamprologusbrichardi.jpeg"
  },
  {
    id: "mesonauta-festivus",
    nomScientifique: "Mesonauta festivus",
    nomCommun: "Cichlidé drapeau",
    ordre: "Cichliformes",
    famille: "Cichlidae",
    genre: "Mesonauta",
    continent: "Amérique du Sud",
    pays: ["Brésil", "Bolivie", "Paraguay"],
    page: "fiche/Mesonauta-festivus.html",
    image: "img/Mesonauta-festivus/Mesonauta-festivus.PNG"
  },
  {
    id: "geophagus-brasiliensis",
    nomScientifique: "Geophagus brasiliensis",
    nomCommun: "Carpe géophage du Brésil",
    ordre: "Cichliformes",
    famille: "Cichlidae",
    genre: "Geophagus",
    continent: "Amérique du Sud",
    pays: ["Brésil", "Uruguay"],
    page: "fiche/Geophagus-brasiliensis.html",
    image: "img/Geophagus-brasilensis/Geophagus-brasilensis.PNG"
  },
  {
    id: "ilyodon-furcidens",
    nomScientifique: "Ilyodon furcidens",
    nomCommun: "Goodeidae truite dorée",
    ordre: "Cyprinodontiformes",
    famille: "Goodeidae",
    genre: "Ilyodon",
    continent: "Amérique du Nord",
    pays: ["Mexique"],
    page: "fiche/Ilyodon-furcidens.html",
    image: "img/Ilyodon-furcidens/Ilyodon-furcidens.png"
  },
  {
    id: "xiphophorus-variatus",
    nomScientifique: "Xiphophorus variatus",
    nomCommun: "Platy variatus",
    ordre: "Cyprinodontiformes",
    famille: "Poeciliidae",
    genre: "Xiphophorus",
    continent: "Amérique du Nord",
    pays: ["Mexique"],
    page: "fiche/Xiphophorus-variatus.html",
    image: "img/Xiphophorus-variatus/Xiphophorus-variatus.PNG"
  },
  {
    id: "xiphophorus-hellerii",
    nomScientifique: "Xiphophorus hellerii",
    nomCommun: "Porte-épée",
    ordre: "Cyprinodontiformes",
    famille: "Poeciliidae",
    genre: "Xiphophorus",
    continent: "Amérique du Nord",
    pays: ["Mexique", "Amérique centrale"],
    page: "fiche/Xiphophorus-helleii.html",
    image: "img/Xiphophorus-hellerii/Xiphophorus-hellerii.PNG"
  },
  {
    id: "xenotoca-eiseni",
    nomScientifique: "Xenotoca eiseni",
    nomCommun: "Xénotoque d’Eisen",
    ordre: "Cyprinodontiformes",
    famille: "Goodeidae",
    genre: "Xenotoca",
    continent: "Amérique du Nord",
    pays: ["Mexique"],
    page: "fiche/Xenotoca-eiseni.html",
    image: "img/Xenotoca-eiseni/Xenotoca-eiseni.PNG"
  },
  {
    id: "ctenops-nobilis",
    nomScientifique: "Ctenops nobilis",
    nomCommun: "Gourami noble",
    ordre: "Anabantiformes",
    famille: "Osphronemidae",
    genre: "Ctenops",
    continent: "Asie",
    pays: ["Inde", "Bangladesh"],
    page: "fiche/Ctenops-nobilis.html",
    image: "img/Ctenops-nobilis/Ctenops-nobilis.jpg"
  },
  {
    id: "rubricatochromis-bimaculatus",
    nomScientifique: "Rubricatochromis bimaculatus",
    nomCommun: "Cichlidé joyau",
    ordre: "Cichliformes",
    famille: "Cichlidae",
    genre: "Rubricatochromis",
    continent: "Afrique",
    pays: ["Sénégal", "Guinée", "Sierra Leone", "Libéria"],
    page: "fiche/Rubricatochromis-bimaculatus.html",
    image: "img/Rubricatochromis-bimaculatus/Rubricatochromis-bimaculatus.jpg"
  },
  {
    id: "bedotia-madagascariensis",
    nomScientifique: "Bedotia madagascariensis",
    nomCommun: "Bedotia de Madagascar",
    ordre: "Atheriniformes",
    famille: "Bedotiidae",
    genre: "Bedotia",
    continent: "Afrique",
    pays: ["Madagascar"],
    page: "fiche/Bedotia-madagacariensis.html",
    image: "img/Bedotia-madagascariensis/Bedotia-madahascariensis.jpeg"
  },
  {
    id: "alestropetersius-brichardi",
    nomScientifique: "Alestopetersius brichardi",
    nomCommun: "Tétra de Brichard",
    ordre: "Characiformes",
    famille: "Alestidae",
    genre: "Alestopetersius",
    continent: "Afrique",
    pays: ["République démocratique du Congo"],
    page: "fiche/Alestopetersus-brichardi.html",
    image: "img/Alestopetersius-brichardi/Alestopetersius-brichardi.jpeg"
  },
  {
    id: "pseudomugil-connieae",
    nomScientifique: "Pseudomugil connieae",
    nomCommun: "Pseudomugil de Connie",
    ordre: "Atheriniformes",
    famille: "Pseudomugilidae",
    genre: "Pseudomugil",
    continent: "Océanie",
    pays: ["Papouasie-Nouvelle-Guinée"],
    page: "fiche/Pseudomugil-connieae.html",
    image: "img/Pseudomugil-connieae/Pseudomugil-connieae.jpeg"
  },
  {
    id: "heterandria-formosa",
    nomScientifique: "Heterandria formosa",
    nomCommun: "Moustique du Heterandria",
    ordre: "Cyprinodontiformes",
    famille: "Poeciliidae",
    genre: "Heterandria",
    continent: "Amérique du Nord",
    pays: ["États-Unis"],
    page: "fiche/Heterandria-formosa.html",
    image: "img/Heterandria-formosa/Heterandria-formosa.jpeg"
  },
  {
    id: "neolamprologus-multifasciatus",
    nomScientifique: "Neolamprologus multifasciatus",
    nomCommun: "",
    ordre: "Cichliformes",
    famille: "Cichlidae",
    genre: "Neolamprologus",
    continent: "Afrique",
    pays: ["Zambie", "Tanzanie", "République démocratique du Congo"],
    page: "fiche/Neolamprologus-multifasciatus.html",
    image: "img/Neolamprologus-multifasciatus/Neolamprologus-multifasciatus.jpeg"
  },
  {
    id: "astronotus-mikoljii",
    nomScientifique: "Astronotus mikoljii",
    nomCommun: "Oscar de l’Orénoque",
    ordre: "Cichliformes",
    famille: "Cichlidae",
    genre: "Astronotus",
    continent: "Amérique du Sud",
    pays: ["Venezuela", "Colombie"],
    page: "fiche/Astronotus-mikoljii.html",
    image: "img/Astronotus-mikoljii/Astronotus-mikoljii.jpeg"
  },
  {
    id: "limia-nigrofasciata",
    nomScientifique: "Limia nigrofasciata",
    nomCommun: "Limia à dos bossu",
    ordre: "Cyprinodontiformes",
    famille: "Poeciliidae",
    genre: "Limia",
    continent: "Amérique du Nord",
    pays: ["République dominicaine"],
    page: "fiche/Limia-nigrofasciata.html",
    image: "img/Limia-nigrofasciata/Limia-nigrofasciata.jpeg"
  },
  {
    id: "limia-tridens",
    nomScientifique: "Limia tridens",
    nomCommun: "Limia tridens",
    ordre: "Cyprinodontiformes",
    famille: "Poeciliidae",
    genre: "Limia",
    continent: "Amérique du Nord",
    pays: ["République dominicaine"],
    page: "fiche/Limia-tridens.html",
    image: "img/Limia-tridens/Limia-tridens.jpeg"
  },
  {
    id: "tateurdina-ocellicauda",
    nomScientifique: "Tateurdina ocellicauda",
    nomCommun: "Gobie paon",
    ordre: "Perciformes",
    famille: "Eleotridae",
    genre: "Tateurdina",
    continent: "Océanie",
    pays: ["Papouasie-Nouvelle-Guinée"],
    page: "fiche/Tateurdina-ocellicauda.html",
    image: "img/Tateurdina-ocellicauda/Tateurdina-ocellicauda.jpeg"
  },
  {
    id: "betta-persephone",
    nomScientifique: "Betta persephone",
    nomCommun: "Betta persephone",
    ordre: "Anabantiformes",
    famille: "Osphronemidae",
    genre: "Betta",
    continent: "Asie",
    pays: ["Malaisie"],
    page: "fiche/Betta-persephone.html",
    image: "img/Betta-persephone/Betta-persephone.jpeg"
  },
  {
    id: "betta-hendra",
    nomScientifique: "Betta hendra",
    nomCommun: "Betta hendra",
    ordre: "Anabantiformes",
    famille: "Osphronemidae",
    genre: "Betta",
    continent: "Asie",
    pays: ["Indonésie"],
    page: "fiche/Betta-hendra.html",
    image: "img/Betta-hendra/Betta-hendra.jpeg"
  },
  {
    id: "poecilia-latipinna",
    nomScientifique: "Poecilia latipinna",
    nomCommun: "Molly voilé",
    ordre: "Cyprinodontiformes",
    famille: "Poeciliidae",
    genre: "Poecilia",
    continent: "Amérique du Nord",
    pays: ["États-Unis", "Mexique"],
    page: "fiche/Poecilia-latipinna.html",
    image: "img/Poecilia-latipinna/Poecilia-latipinna.jpeg"
  },
  {
    id: "xiphophorus-pygmaeus",
    nomScientifique: "Xiphophorus pygmaeus",
    nomCommun: "Xipho pygmée",
    ordre: "Cyprinodontiformes",
    famille: "Poeciliidae",
    genre: "Xiphophorus",
    continent: "Amérique du Nord",
    pays: ["Mexique"],
    page: "fiche/Xiphophorus-pygmaeus.html",
    image: "img/Xiphophorus-pygmaeus/Xiphophorus-pygmaeus.jpeg"
  },
  {
    id: "paracheirodon-axelrodi",
    nomScientifique: "Paracheirodon axelrodi",
    nomCommun: "Néon cardinalis",
    ordre: "Characiformes",
    famille: "Characidae",
    genre: "Paracheirodon",
    continent: "Amérique du Sud",
    pays: ["Brésil", "Colombie", "Venezuela"],
    page: "fiche/Paracheirodon-axelrodo.html",
    image: "img/Paracheirodon-axelrodi/imgParacheirodonaxelrodi.jpeg"
  },
  {
    id: "paracheirodon-innesi",
    nomScientifique: "Paracheirodon innesi",
    nomCommun: "Néon bleu",
    ordre: "Characiformes",
    famille: "Characidae",
    genre: "Paracheirodon",
    continent: "Amérique du Sud",
    pays: ["Pérou", "Colombie", "Brésil"],
    page: "fiche/Paracheirodon-innesi.html",
    image: "img/Paracheirodon-innesi/imgparacheirodoninnesi.jpeg"
  },
  {
    id: "paracheirodon-simulans",
    nomScientifique: "Paracheirodon simulans",
    nomCommun: "Néon vert",
    ordre: "Characiformes",
    famille: "Characidae",
    genre: "Paracheirodon",
    continent: "Amérique du Sud",
    pays: ["Brésil"],
    page: "fiche/Paracheirodon-simulans.html",
    image: "img/Paracheirodon-simulans/imgParacheirodonsimulans.jpeg"
  },
  {
    id: "hemigrammus-bleheris",
    nomScientifique: "Hemigrammus bleheris",
    nomCommun: "Hemigrammus",
    ordre: "Characiformes",
    famille: "Characidae",
    genre: "Hemigrammus",
    continent: "Amérique du Sud",
    pays: ["Brésil","Colombie"],
    page: "fiche/Hemigrammus-bleheris.html",
    image: "img/Hemigrammus-bleheri/imgHemigrammausbleheri.jpeg"
  },
  {
    id: "malpulutta-kretseri",
    nomScientifique: "Malpulutta kretseri",
    nomCommun: "",
    ordre: "Anabantiformes",
    famille: "Osphronemidae",
    genre: "Malpulutta",
    continent: "Asie",
    pays: ["Sri Lanka"],
    page: "fiche/Malpulutta-kretseri.html",
    image: "img/Malpulutta-kretseri/imgMalpuluttakretseri.jpeg"
  },
  {
    id: "pseudosphromenus-cupanus",
    nomScientifique: "Pseudosphromenus cupanus",
    nomCommun: "",
    ordre: "Anabantiformes",
    famille: "Osphronemidae",
    genre: "Pseudosphromenus",
    continent: "Asie",
    pays: ["Inde", "Sri Lanka"],
    page: "fiche/Pseudosphromenus-cupanus.html",
    image: "img/Pseudosphromenus-cupanus/imgpseudosphromenuscupanus.jpeg"
  },
  {
    id: "pseudosphromenus-dayi",
    nomScientifique: "Pseudosphromenus dayi",
    nomCommun: "",
    ordre: "Anabantiformes",
    famille: "Osphronemidae",
    genre: "Pseudosphromenus",
    continent: "Asie",
    pays: ["Inde"],
    page: "fiche/Pseudosphromenus-dayi.html",
    image: "img/Pseudosphromenus-dayi/img-Pseudosphromenusdayi.jpeg"
  },
  {
    id: "zoogoneticus-tequila",
    nomScientifique: "Zoogoneticus tequila",
    nomCommun: "",
    ordre: "Cyprinodontiformes",
    famille: "Goodeidae",
    genre: "Zoogoneticus",
    continent: "Amérique du Nord",
    pays: ["Mexique"],
    page: "fiche/Zoogoneticus-tequila.html",
    image: "img/Zoogoneticus-tequila/Zoogoneticustequila.jpeg"
  },
  {
    id: "macropodus-spechti",
    nomScientifique: "Macropodus spechti",
    nomCommun: "Macropode noir",
    ordre: "Anabantiformes",
    famille: "Osphronemidae",
    genre: "Macropodus",
    continent: "Asie",
    pays: ["Vietnam"],
    page: "fiche/Macropodus-spechti.html",
    image: "img/Macropodus-spechti/img-Macropodusspechti.jpeg"
  },
  {
    id: "macropodus-ocellatus",
    nomScientifique: "Macropodus ocellatus",
    nomCommun: "",
    ordre: "Anabantiformes",
    famille: "Osphronemidae",
    genre: "Macropodus",
    continent: "Asie",
    pays: ["Chine", "Corée", "Russie"],
    page: "fiche/Macropodus-ocellatus.html",
    image: "img/Macropodus-ocellatus/imgMacropodusocellatus.jpeg"
  },
  {
    id: "macropodus-opercularis",
    nomScientifique: "Macropodus opercularis",
    nomCommun: "Poisson-paradis",
    ordre: "Anabantiformes",
    famille: "Osphronemidae",
    genre: "Macropodus",
    continent: "Asie",
    pays: ["Chine", "Vietnam", "Corée"],
    page: "fiche/Macropodus-opercularis.html",
    image: "img/Macropodus-opercularis/imgMacropodusopercularis.jpeg"
  }
];
